In [0]:
'''
Steven Jordan 
20/11/2019
In this file, I import the train and test files for each of the city sector datasets and run a 
Random Forest Regressor using identical parameters, which we previously determined to be the 
parameters that will produce the most high scoring but parsimonious model
'''


import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 365)
pd.set_option('display.max_columns', 365)
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, explained_variance_score



In [0]:
food_train = pd.read_csv('food_train.csv', index_col=False)
groc_train = pd.read_csv('groc_train.csv', index_col=False)
heal_train = pd.read_csv('heal_train.csv', index_col=False)
k12_train = pd.read_csv('k12_train.csv', index_col=False)
lodg_train = pd.read_csv('lodg_train.csv', index_col=False)
off_train = pd.read_csv('off_train.csv', index_col=False)
res_train = pd.read_csv('res_train.csv', index_col=False)
sar_train = pd.read_csv('sar_train.csv', index_col=False)

food_test = pd.read_csv('food_test.csv', index_col=False)
groc_test = pd.read_csv('groc_test.csv', index_col=False)
heal_test = pd.read_csv('heal_test.csv', index_col=False)
k12_test = pd.read_csv('k12_test.csv', index_col=False)
lodg_test = pd.read_csv('lodg_test.csv', index_col=False)
off_test = pd.read_csv('off_test.csv', index_col=False)
res_test = pd.read_csv('res_test.csv', index_col=False)
sar_test = pd.read_csv('sar_test.csv', index_col=False)

In [0]:
food_x = food_train.drop(columns = ['Electricity_KW_AVG'])
groc_x = groc_train.drop(columns = ['Electricity_KW_AVG'])
heal_x = heal_train.drop(columns = ['Electricity_KW_AVG'])
k12_x = k12_train.drop(columns = ['Electricity_KW_AVG'])
lodg_x = lodg_train.drop(columns = ['Electricity_KW_AVG'])
off_x = off_train.drop(columns = ['Electricity_KW_AVG'])
res_x = res_train.drop(columns = ['Electricity_KW_AVG'])
sar_x = sar_train.drop(columns = ['Electricity_KW_AVG'])

food_y = food_train['Electricity_KW_AVG']
groc_y = groc_train['Electricity_KW_AVG']
heal_y = heal_train['Electricity_KW_AVG']
k12_y = k12_train['Electricity_KW_AVG']
lodg_y = lodg_train['Electricity_KW_AVG']
off_y = off_train['Electricity_KW_AVG']
res_y = res_train['Electricity_KW_AVG']
sar_y = sar_train['Electricity_KW_AVG']

In [0]:
food_x_test = food_test.drop(columns = ['Electricity_KW_AVG'])
groc_x_test = groc_test.drop(columns = ['Electricity_KW_AVG'])
heal_x_test = heal_test.drop(columns = ['Electricity_KW_AVG'])
k12_x_test = k12_test.drop(columns = ['Electricity_KW_AVG'])
lodg_x_test = lodg_test.drop(columns = ['Electricity_KW_AVG'])
off_x_test = off_test.drop(columns = ['Electricity_KW_AVG'])
res_x_test = res_test.drop(columns = ['Electricity_KW_AVG'])
sar_x_test = sar_test.drop(columns = ['Electricity_KW_AVG'])

food_y_test = food_test['Electricity_KW_AVG']
groc_y_test = groc_test['Electricity_KW_AVG']
heal_y_test = heal_test['Electricity_KW_AVG']
k12_y_test = k12_test['Electricity_KW_AVG']
lodg_y_test = lodg_test['Electricity_KW_AVG']
off_y_test = off_test['Electricity_KW_AVG']
res_y_test = res_test['Electricity_KW_AVG']
sar_y_test = sar_test['Electricity_KW_AVG']

In [0]:
food_rgr = RandomForestRegressor(max_features=0.7, min_samples_leaf=1, min_samples_split=3, n_estimators=410, random_state=3)
groc_rgr = RandomForestRegressor(max_features=0.7, min_samples_leaf=1, min_samples_split=3, n_estimators=410, random_state=3)
heal_rgr = RandomForestRegressor(max_features=0.7, min_samples_leaf=1, min_samples_split=3, n_estimators=410, random_state=3)
k12_rgr = RandomForestRegressor(max_features=0.7, min_samples_leaf=1, min_samples_split=3, n_estimators=410, random_state=3)
lodg_rgr = RandomForestRegressor(max_features=0.7, min_samples_leaf=1, min_samples_split=3, n_estimators=410, random_state=3)
off_rgr = RandomForestRegressor(max_features=0.7, min_samples_leaf=1, min_samples_split=3, n_estimators=410, random_state=3)
res_rgr = RandomForestRegressor(max_features=0.7, min_samples_leaf=1, min_samples_split=3, n_estimators=410, random_state=3)
sar_rgr = RandomForestRegressor(max_features=0.7, min_samples_leaf=1, min_samples_split=3, n_estimators=410, random_state=3)


In [0]:
food_rgr.fit(food_x, food_y)
groc_rgr.fit(groc_x, groc_y)
heal_rgr.fit(heal_x, heal_y)
k12_rgr.fit(k12_x, k12_y)
lodg_rgr.fit(lodg_x, lodg_y)
off_rgr.fit(off_x, off_y)
res_rgr.fit(res_x, res_y)
sar_rgr.fit(sar_x, sar_y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features=0.7, max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=3,
           min_weight_fraction_leaf=0.0, n_estimators=410, n_jobs=None,
           oob_score=False, random_state=3, verbose=0, warm_start=False)

In [0]:
preds = food_rgr.predict(food_x_test) + groc_rgr.predict(groc_x_test) + heal_rgr.predict(heal_x_test) + k12_rgr.predict(k12_x_test) +lodg_rgr.predict(lodg_x_test) + off_rgr.predict(off_x_test) + res_rgr.predict(res_x_test) + sar_rgr.predict(sar_x_test) 

In [0]:
preds

array([ 95690.90044404,  82541.17291292, 101069.11484713, 105137.67585409,
       108664.39610406, 100053.96631354,  98748.57286157,  79833.60688785,
        80810.86987587,  91480.9970384 ,  88101.83074201,  91214.9724556 ,
       101527.85075034,  81062.46335135, 113400.79877031, 127215.79063586,
       100609.70438379, 112292.79900961, 108764.42521649,  94955.08601734,
       109510.12340532, 100364.92110735, 112948.05662805, 117421.8308745 ,
       111081.41775408,  87527.16274948,  90112.21680603, 151772.05548779,
       108775.13451741, 101290.79379078,  99975.63887805,  96707.75511643,
        97951.14271521,  96373.66700222, 124169.54599341, 122876.62627736,
        98585.43804302,  85303.8129208 , 122245.54850118,  79035.53543435,
        96962.89831712, 124353.61705023,  79767.578577  ,  85269.92055983,
        95780.46426656, 103267.39517125,  98653.76170749,  99132.20803688,
        90846.36492114, 106527.34544255,  88502.23588951,  85419.78804421,
        98209.23683254,  

In [0]:
actuals = np.array(food_y_test) + np.array(groc_y_test) + np.array(heal_y_test) + np.array(k12_y_test) + np.array(lodg_y_test) + np.array(off_y_test) + np.array(res_y_test) + np.array(sar_y_test)

In [0]:
preds

array([ 95690.90044404,  82541.17291292, 101069.11484713, 105137.67585409,
       108664.39610406, 100053.96631354,  98748.57286157,  79833.60688785,
        80810.86987587,  91480.9970384 ,  88101.83074201,  91214.9724556 ,
       101527.85075034,  81062.46335135, 113400.79877031, 127215.79063586,
       100609.70438379, 112292.79900961, 108764.42521649,  94955.08601734,
       109510.12340532, 100364.92110735, 112948.05662805, 117421.8308745 ,
       111081.41775408,  87527.16274948,  90112.21680603, 151772.05548779,
       108775.13451741, 101290.79379078,  99975.63887805,  96707.75511643,
        97951.14271521,  96373.66700222, 124169.54599341, 122876.62627736,
        98585.43804302,  85303.8129208 , 122245.54850118,  79035.53543435,
        96962.89831712, 124353.61705023,  79767.578577  ,  85269.92055983,
        95780.46426656, 103267.39517125,  98653.76170749,  99132.20803688,
        90846.36492114, 106527.34544255,  88502.23588951,  85419.78804421,
        98209.23683254,  

In [0]:
preds.shape

(73,)

In [0]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(actuals, preds)
rmse = np.sqrt(mse)
print(rmse)

from sklearn.metrics import explained_variance_score
r2 = explained_variance_score(actuals, preds)
print(r2)

2963.479381189239
0.964413606237981


In [0]:
preds


array([ 95690.90044404,  82541.17291292, 101069.11484713, 105137.67585409,
       108664.39610406, 100053.96631354,  98748.57286157,  79833.60688785,
        80810.86987587,  91480.9970384 ,  88101.83074201,  91214.9724556 ,
       101527.85075034,  81062.46335135, 113400.79877031, 127215.79063586,
       100609.70438379, 112292.79900961, 108764.42521649,  94955.08601734,
       109510.12340532, 100364.92110735, 112948.05662805, 117421.8308745 ,
       111081.41775408,  87527.16274948,  90112.21680603, 151772.05548779,
       108775.13451741, 101290.79379078,  99975.63887805,  96707.75511643,
        97951.14271521,  96373.66700222, 124169.54599341, 122876.62627736,
        98585.43804302,  85303.8129208 , 122245.54850118,  79035.53543435,
        96962.89831712, 124353.61705023,  79767.578577  ,  85269.92055983,
        95780.46426656, 103267.39517125,  98653.76170749,  99132.20803688,
        90846.36492114, 106527.34544255,  88502.23588951,  85419.78804421,
        98209.23683254,  